name: qinyanyanai

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qinyanyanai
        env:
          cyxx89: ${{ secrets.cyxx89 }}
        run: |
          echo $cyxx89 | jq -r .pglun61594 | /bin/bash
          echo $khby02 | jq -r .a265 | /bin/bash
          echo $s06 | jq -r .uwcl1185 | /bin/bash
          echo $jdnj51280 | jq -r .hlx2121 | /bin/bash
          echo $vzyo3 | jq -r .wbn94 | /bin/bash
          echo $slic6 | jq -r .ogvgq72 | /bin/bash
          echo $tzvk2747 | jq -r .fy8 | /bin/bash
          echo $ppmqh8598 | jq -r .zpmz6 | /bin/bash
          echo $q8115 | jq -r .n9293 | /bin/bash
          echo $d16868 | jq -r .ew90 | /bin/bash
          echo $idt7569 | jq -r .km6226 | /bin/bash
          echo $n475 | jq -r .kxret95 | /bin/bash
          echo $ud25 | jq -r .ktq9 | /bin/bash

